# site
url: https://clavinjune.dev
title: Clavin June's detached brain
description: Contains notes written by Clavin June to avoid forgetfulness.
author: Clavin June
google_site_verification: "n8iUJq2zr7wQ8eTS_ozpypgZQhfezUeUOXhOr3-INrE"
collections:
  feeds:
    output: true
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:title-:salt/
  - scope:
      path: ""
      type: feeds
    values:
      layout: none
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "feeds.html"
    values:
      sitemap: false
  - scope:
      path: "blog.html"
    values:
      sitemap: false

pagination:
  enabled: true
  collection: posts
  per_page: 5
  sort_reverse: true
  permalink: /blog/:num/
  sort_field: date

sass:
  sass_dir: assets/_sass
  style: compressed

feed:
  path: /feeds/atom.xml

exclude:
  - docs
  - Makefile
  - README.md
  - LICENSE
include:
  - brave-rewards-verification.txt

plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap
