[build]
publish = "docs"
command = "echo 1"

[context.production.environment]
HUGO_VERSION = "0.121.1"

[context.deploy-preview.environment]
HUGO_VERSION = "0.121.1"

[context.deploy-preview]
command = "make netlify"
