[build]
publish = "docs"
command = "make serve"

[context.production.environment]
HUGO_VERSION = "0.113.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.113.0"

[context.deploy-preview]
command = "make netlify"
